# Generated by Django 2.1.5 on 2019-04-04 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userdriven_composition', '0004_auto_20190404_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_registry',
            name='api_link',
        ),
        migrations.RemoveField(
            model_name='service_registry',
            name='name_id',
        ),
    ]
