# Generated by Django 2.1.5 on 2019-04-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdriven_composition', '0005_auto_20190404_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_registry',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
