# Generated by Django 2.1.5 on 2019-04-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdriven_composition', '0006_auto_20190407_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_registry',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
